input_template:
  '{

    "## Sample attributes": "",
    "fastq_to_gvcf_wf.sample_name": "",
    "fastq_to_gvcf_wf.batch_id": "plate_1",
    "fastq_to_gvcf_wf.fastq": "",
    "fastq_to_gvcf_wf.ref_fasta": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.fasta",
    "fastq_to_gvcf_wf.ref_fasta_idx": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.fasta.fai",
    "fastq_to_gvcf_wf.ref_fasta_dict": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.dict",
    "fastq_to_gvcf_wf.ref_bwa_amb": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.fasta.amb",
    "fastq_to_gvcf_wf.ref_bwa_ann": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.fasta.ann",
    "fastq_to_gvcf_wf.ref_bwa_bwt": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.fasta.bwt",
    "fastq_to_gvcf_wf.ref_bwa_pac": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.fasta.pac",
    "fastq_to_gvcf_wf.ref_bwa_sa": "s3://odis-refs/odis-draft-assembly-v1-35ctgs/odis.draft_assembly.v1.35ctg.fasta.sa",
    "fastq_to_gvcf_wf.rg_pu": "HWI-ST425:218:HH3WVADXX:1",
    "fastq_to_gvcf_wf.rg_pl": "Illumina",
    "fastq_to_gvcf_wf.headcrop_len": 2

  }'

sample_id_col: fastq_to_gvcf_wf.sample_name

sample_sheet_validators: [validate_ss_against_wdl_template]

wf_type: scatter