input_template:
  '{

    "## Sample attributes": "",
    "stacks_denovo_wf.sample_name": "",
    "stacks_denovo_wf.input_fastqs": "",
    "stacks_denovo_wf.popmap_file": "s3://odis-analysis/ddrad_data/odis_stacks_popmap.txt"
  }'

sample_id_col: stacks_denovo_wf.sample_name

sample_sheet_validators: [validate_ss_against_wdl_template]

wf_type: gather